/**
 * Books API
 * # Introduction This is an **example** API to demonstrate features of OpenAPI specification 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Book model module.
 * @module model/Book
 * @version 1.0.0
 */
class Book {
    /**
     * Constructs a new <code>Book</code>.
     * @alias module:model/Book
     * @param title {String} Book title
     * @param author {String} Book Author
     */
    constructor(title, author) { 
        
        Book.initialize(this, title, author);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, author) { 
        obj['title'] = title;
        obj['author'] = author;
    }

    /**
     * Constructs a <code>Book</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Book} obj Optional instance to populate.
     * @return {module:model/Book} The populated <code>Book</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Book();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Book Id
 * @member {String} id
 */
Book.prototype['id'] = undefined;

/**
 * Book title
 * @member {String} title
 */
Book.prototype['title'] = undefined;

/**
 * Book Author
 * @member {String} author
 */
Book.prototype['author'] = undefined;






export default Book;

