openapi: 3.0.0
info:
  version: 1.0.0
  title: Books API
  x-logo:
    url: "https://zenvia.github.io/zenvia-openapi-spec/zenapi.png"
  description: |
    # Introduction
    This is an **example** API to demonstrate features of OpenAPI specification
servers:
  - url: "http://localhost:3000"
